name: py39
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - ld_impl_linux-aarch64=2.40
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.1
  - libsqlite=3.45.3
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - ncurses=6.5
  - openssl=3.3.0
  - pip=24.0
  - python=3.9.17
  - readline=8.2
  - setuptools=69.5.1
  - tk=8.6.13
  - wheel=0.43.0
  - xz=5.2.6
  - pip:
    - absl-py==2.1.0
    - argparse==1.4.0
    - astunparse==1.6.3
    - cachetools==5.3.3
    - certifi==2024.2.2
    - charset-normalizer==3.3.2
    - flatbuffers==20181003210633
    - gast==0.4.0
    - google-auth==2.29.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.63.0
    - h5py==3.10.0
    - idna==3.7
    - keras==2.10.0
    - keras-preprocessing==1.1.2
    - libclang==18.1.1
    - markdown==3.6
    - markupsafe==2.1.5
    - numpy==1.26.4
    - oauthlib==3.2.2
    - opencv-python==4.9.0.80
    - opt-einsum==3.3.0
    - packaging==24.0
    - pandas==2.2.2
    - protobuf==3.19.6
    - pyasn1==0.6.0
    - pyasn1-modules==0.4.0
    - pybind11==2.12.0
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - requests==2.31.0
    - requests-oauthlib==2.0.0
    - rsa==4.9
    - six==1.16.0
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.10.1
    - tensorflow-cpu-aws==2.10.1
    - tensorflow-estimator==2.10.0
    - tensorflow-io-gcs-filesystem==0.37.0
    - termcolor==2.4.0
    - tflite-runtime==2.14.0
    - tflite-support==0.4.4
    - typing-extensions==4.11.0
    - tzdata==2024.1
    - urllib3==2.2.1
    - werkzeug==3.0.3
    - wrapt==1.16.0
